networks:
  saas-network:
    external: true
  # app-network:
  #   external: true

volumes:
  backup-temp:

services:
  backup-worker:
    container_name: backup_worker
    image: db_backup:prod
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    expose:
      - 5000
    # ports:
    #   - '5000:5000'
    env_file:
      - .env
    networks:
      - saas-network
      # - app-network
    volumes:
      - backup-temp:/tmp
