networks:
  saas-network:
    external: true

volumes:
  backup-temp:

services:
  backup-worker:
    container_name: backup_worker

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - saas-network
    volumes:
      - backup-temp:/tmp
